### ISSUE TITLE
Optimize AgileTs for tree-shaking

### ISSUE THREAD

**Issue by bennodev19** [agile-ts/agile#186]
### ❓ Is your feature request related to a problem? 
Big bundle size

### 📄 Describe the solution you'd like
As a user I want my application to be as small as possible,
thus, I don't want to have unused functionalities of AgileTs in my production build.

### 📃 Describe alternatives you've considered
No alternative

### ➕ Additional Notes
- https://dev.to/lukasbombach/how-to-write-a-tree-shakable-component-library-4ied
- https://redd.one/blog/building-a-tree-shakable-library-with-rollupjs
- https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking
- https://blog.theodo.com/2021/04/library-tree-shaking/ 💪

### 💪 TODO
- [x] Treeshake Collection
- [x] Treeshake Computed
- [x] Treeshake Logger (-> only logCodes in prod instead of whole messages)
- [x] Treeshake unused Hooks/HOC's
- [x] Treeshake Storage functionality

**Comment by bennodev19** [comment]
an interesting thread
![image](https://user-images.githubusercontent.com/57860196/129672033-91b6f6a9-8d2c-42c6-abe6-73adec7a4549.png)
https://github.com/webpack/webpack/issues/9337

**Comment by bennodev19** [comment]
https://webpack.js.org/guides/tree-shaking/

**Comment by bennodev19** [comment]
https://github.com/agile-ts/agile/pull/188
